services:
  bun:
    build:
      target: production
    restart: unless_stopped
    networks:
      - application

  redis:
    image: redis
    networks:
      - application
    restart: unless_stopped
    volumes:
      - redis:/data

networks:
  application:

volumes:
  redis: